name: ForceItemBattleTeams
version: '${version}'

main: ben.spiel.ForceItemBattleTeams
api-version: '1.21.11'
load: POSTWORLD

commands:
  forceitembattle:
    description: Hauptcommand für Force Item Battle Teams
    usage: /forceitembattle <start|stop|settings|lock|restart|reveal|overview|backpack>
    aliases: [fib]

  backpack:
    description: Öffnet den Team-Backpack
    usage: /backpack



permissions:
  fib.start:
    description: Erlaubt Admin-Commands für Force Item Battle Teams
    default: op
