name: ForceItemBattleTeams
version: '${version}'

main: ben.spiel.ForceItemBattleTeams
api-version: '1.21.10'
load: POSTWORLD

commands:
  forceitembattle:
    usage: /forceitembattle <start|stop|settings|lock|restart>

  backpack:
    usage: /backpack


permissions:
  fib.start:
    default: op